AppBundle\Entity\Region:
    type: entity
    table: null
    repositoryClass: AppBundle\Entity\RegionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
        maxmembers:
            type: integer
    lifecycleCallbacks: {  }
